//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Getfund.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donation
    {

        public int DonationId { get; set; }
        public Nullable<int> ID { get; set; }
        public Nullable<int> PId { get; set; }
        public string DonateDes { get; set; }
        public string DonateTime { get; set; }
        public string transaction_id { get; set; }
        public int Amount { get; set; }
    
        public virtual GUser GUser { get; set; }
        public virtual Project Project { get; set; }
    }
}
